name: build

on:
  release:
    types: [published]
  
permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pyinstaller
          pip install pillow
          pip3 install -r "requirements.txt"

      - name: Build tpp using tppbuild
        run: |
          python3 "./build.py"

      - name: Uploading tpp for Windows
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "./*.tpp"
          overwrite: true
          file_glob: true

build-macos:
  runs-on: macos-latest
  steps:
    - uses: actions/checkout@v3

    - name: Install PortAudio development headers
      run: |
        brew update
        brew install portaudio

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install pyinstaller
        pip install pillow
        pip3 install -r "requirements.txt"

    - name: Build tpp using tppbuild
      run: |
        python3 "./build.py"

    - name: Uploading tpp for macOS
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: "./*.tpp"
        overwrite: true
        file_glob: true


  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies on Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y portaudio19-dev  # Install portaudio header

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pyinstaller
          pip install pillow
          pip3 install -r "requirements.txt"

      - name: Build tpp using tppbuild
        run: |
          python3 "./build.py"

      - name: Uploading tpp for Ubuntu
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "./*.tpp"
          overwrite: true
          file_glob: true
